#!/usr/bin/env python
from scapy.all import *

# VARIABLES
src = sys.argv[1]
dst = sys.argv[2]
sport = random.randint(1024,65535)
dport = int(sys.argv[3])

# SYN
ip=IP(src=src,dst=dst)
SYN=TCP(sport=sport,dport=dport,flags='S',seq=1000,options=[('MSS',0)])
SYNACK=sr1(ip/SYN)

# ACK
ACK=TCP(sport=sport, dport=dport, flags='A', seq=SYNACK.ack, ack=SYNACK.seq + 1)
send(ip/ACK)

getStr = 'GET / HTTP/1.1\r\nHost: ' + dst + '\r\n\r\n'

request = ip/ACK/getStr
reply = sr1(request)
print reply.show()
